remote_theme: baagaard-usgs/just-the-docs
title: San Francisco Bay region seismic velocity model development
baseurl: /sfcvm-website

color_scheme: usgs_lightbg
heading_anchors: false
search_enabled: true

title_image: images/USGSsimple.png
software_version: 2
